name: CI
# This workflow is triggered on pushes to the repository's main branch.
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Lint on ${{ matrix.os }}, Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x, latest]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Deps
        run: npm ci
      - name: Lint JavaScript
        run: npm run lint
      - name: Build Selenium DriverProvider JAR
        run: npm run jar
